# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql
  encoding: utf8
  database: upload
  username: root
  password: Jack9007
  host: localhost
test:
  adapter: mysql
  encoding: utf8
  database: upload
  username: root
  password: Jack9007
  host: localhost
production:
  adapter: mysql
  encoding: utf8
  database: upload
  username: root
  password: Jack9007
  host: localhost
